export const ADD_POST_INIT = 'ADD_POST_INIT'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'

export const FETCH_POSTS_INIT = 'FETCH_POSTS_INIT'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'

export const FETCH_NEXT_POSTS_INIT = 'FETCH_NEXT_POSTS_INIT'
export const FETCH_NEXT_POSTS_SUCCESS = 'FETCH_NEXT_POSTS_SUCCESS'
export const FETCH_NEXT_POSTS_FAIL = 'FETCH_NEXT_POSTS_FAIL'

export const OUT_OF_POSTS = 'OUT_OF_POSTS'

export const FETCH_REPLIES_INIT = 'FETCH_REPLIES_INIT'
export const FETCH_REPLIES_SUCCESS = 'FETCH_REPLIES_SUCCESS'
export const FETCH_REPLIES_FAIL = 'FETCH_REPLIES_FAIL'

export const ADD_REPLY_INIT = 'ADD_REPLY_INIT'
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS'
export const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL'

export const SIGNUP_INIT = 'SIGNUP_INIT'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const SIGNIN_INIT = 'SIGNIN_INIT'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'

export const SIGNOUT_INIT = 'SIGNOUT_INIT'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL'

export const CLEAR_ERROR = 'CLEAR_ERROR'
